language: node_js
node_js:
  - 'lts/Carbon'

sudo: false
dist: trusty

cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"

env:
  - EMBER_TRY_SCENARIO=default
  - EMBER_TRY_SCENARIO=ember-1.13
  - EMBER_TRY_SCENARIO=ember-2.0
  - EMBER_TRY_SCENARIO=ember-2.1
  - EMBER_TRY_SCENARIO=ember-3.0
  - EMBER_TRY_SCENARIO=ember-3.5
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"

script:
  - ember try $EMBER_TRY_SCENARIO test
