language: node_js
node_js:
  - 'lts/Carbon'

sudo: false
dist: trusty

before_install:
  - npm i npm@6.1.0 -g

script: xvfb-run --server-args="-screen 0 1024x768x24" npm test

notifications:
  email: false
